### ISSUE TITLE
Issue upgrading to 11.2.0

### ISSUE THREAD

**Issue by u01jmg3** [jprichardson/node-fs-extra#1029]
- **Operating System:**

Ubuntu 22.04

- **Node.js version:**

20.5.1

- **`fs-extra` version:**

11.2.0

---

- Upgrading from 11.1.1 (previously working) to 11.2.0 has caused an issue with my CI pipeline and building assets:

```
[webpack-cli] TypeError: Cannot use 'in' operator to search for 'clobber' in 0
    at Object.copy (/home/runner/work/github-actions/github-actions/laravel/node_modules/fs-extra/lib/copy/copy.js:15:28)
    at Object.copy (/home/runner/work/github-actions/github-actions/laravel/node_modules/universalify/index.js:22:13)
    at /home/runner/work/github-actions/github-actions/laravel/webpack.mix.js:47:16
    at new Promise (<anonymous>)
    at /home/runner/work/github-actions/github-actions/laravel/webpack.mix.js:46:16
    at /home/runner/work/github-actions/github-actions/laravel/node_modules/laravel-mix/src/Dispatcher.js:39:62
    at Array.map (<anonymous>)
    at Dispatcher.fire (/home/runner/work/github-actions/github-actions/laravel/node_modules/laravel-mix/src/Dispatcher.js:39:47)
    at Mix.dispatch (/home/runner/work/github-actions/github-actions/laravel/node_modules/laravel-mix/src/Mix.js:248:32)
    at Mix.init (/home/runner/work/github-actions/github-actions/laravel/node_modules/laravel-mix/src/Mix.js:134:21)
```

- Is there a breaking change not mentioned in the changelog? Would you happen to have a recommendation on how to fix this issue?

**Comment by u01jmg3** [comment]
Thanks for pointing me in the right direction. Found the culprit. Appreciate your time.
