### ISSUE TITLE
fs.rmSync is not a function

### ISSUE THREAD

**Issue by kiccer** [jprichardson/node-fs-extra#1030]
```
E:\Lynch Bel\workspace\glms-web\node_modules\fs-extra\lib\remove\index.js:11
  fs.rmSync(path, { recursive: true, force: true })
     ^

TypeError: fs.rmSync is not a function
    at Object.removeSync (E:\Lynch Bel\workspace\glms-web\node_modules\fs-extra\lib\remove\index.js:11:6)
    at items.forEach.item (E:\Lynch Bel\workspace\glms-web\node_modules\fs-extra\lib\empty\index.js:30:12)
    at Array.forEach (<anonymous>)
    at Object.emptyDirSync (E:\Lynch Bel\workspace\glms-web\node_modules\fs-extra\lib\empty\index.js:28:9)
    at Object.<anonymous> (E:\Lynch Bel\workspace\glms-web\postinstall.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

v11.2.0

**Comment by RyanZim** [comment]
What Node.js version are you using?

**Comment by RyanZim** [comment]
Closing for lack of response
