### ISSUE TITLE
fsExtra.move(filepath, newPath) broken;

### ISSUE THREAD

**Issue by luozhihua** [jprichardson/node-fs-extra#128]
```
TypeError: Cannot read property 'mkdirp' of undefined
  at Object.fs.move (/Users/colin/Projects/magicscenes/node_modules/fs-extra/lib/index.js:50:11)
  at Object.module.exports.exports.uploader [as handle] (/Users/colin/Projects/magicscenes/mock-server.js:181:13)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:194:15)
  at Function.app.handle (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:202:3)
  at Object.fn [as handle] (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:74:14)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:194:15)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:130:23)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:169:78)
  at Function.app.handle (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:202:3)
  at Object.fn [as handle] (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:74:14)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:194:15)
  at next (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:130:23)
  at Form.<anonymous> (/Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/lib/middleware/multipart.js:154:29)
  at Form.emit (events.js:129:20)
  at /Users/colin/Projects/magicscenes/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/multiparty/index.js:539:12
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by jprichardson** [comment]
Will you paste the snippet that you're calling it with?

**Comment by jprichardson** [comment]
Oh, you're not passing in a callback, that's why.

Do this:

```js
fs.move(oldPath, newPath, function (err) {
  console.dir(err)
})
```

**Comment by luozhihua** [comment]
Thanks!
