### ISSUE TITLE
ENOTEMPTY is thrown on removeSync 

### ISSUE THREAD

**Issue by gkorland** [jprichardson/node-fs-extra#178]
I got the following error when running ```fs.removeSync()``` on Windows:

```javascript
on uncaughtException: ENOTEMPTY, directory not empty 'D:\\home\\site\\wwwroot\\public\\frontend\\css',

Error: ENOTEMPTY, directory not empty 'D:\\home\\site\\wwwroot\\public\\frontend\\css'    
at Object.fs.rmdirSync (fs.js:623:18)    
at rmkidsSync (D:\\home\\site\\wwwroot\\node_modules\\fs-extra\\node_modules\\rimraf\\rimraf.js:332:11)    
at rmdirSync (D:\\home\\site\\wwwroot\\node_modules\\fs-extra\\node_modules\\rimraf\\rimraf.js:322:7)   
at Function.rimrafSync [as sync] (D:\\home\\site\\wwwroot\\node_modules\\fs-extra\\node_modules\\rimraf\\rimraf.js:293:9)   
at Object.removeSync (D:\\home\\site\\wwwroot\\node_modules\\fs-extra\\lib\\remove\\index.js:4:17)   
at module.exports (D:\\home\\site\\wwwroot\\lib\\express\\server\\index.js:52:8) 
```

**Comment by gkorland** [comment]
It seems like there are many issues regarding this error in rimraf e.g. https://github.com/isaacs/rimraf/issues/25
