### ISSUE TITLE
copy method's argument options couldn't be undefined

### ISSUE THREAD

**Issue by zaaack** [jprichardson/node-fs-extra#203]
```
D:\nodejs\cur_npm\node_modules\fs-extra\lib\copy\ncp.js:17
  var filter = options.filter
                      ^
TypeError: Cannot read property 'filter' of undefined
    at ncp (D:\nodejs\cur_npm\node_modules\fs-extra\lib\copy\ncp.js:17:23)
    at D:\nodejs\cur_npm\node_modules\fs-extra\lib\copy\copy.js:28:29
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)


```

**Comment by jprichardson** [comment]
Thanks, I'll look this over.

**Comment by ColinEberhardt** [comment]
:+1: just hit this issue too

**Comment by jprichardson** [comment]
To be clear, when you call `fs.copy()`, you must include a callback. Maybe I should improve the error message?

**Comment by ColinEberhardt** [comment]
> Maybe I should improve the error message?

That would certainly help - I expected the callback to be optional.

**Comment by RyanZim** [comment]
@jprichardson Is it really necessary to do a special error check to make sure that the callback wasn't omitted? That would just add complexity for little benefit IMO.
