### ISSUE TITLE
copy doesn't return a yieldable value

### ISSUE THREAD

**Issue by cmroanirgo** [jprichardson/node-fs-extra#337]
Using bluebird as recommended, I tried to use promisify on the copy command.

This is the output:

> copying begun
> FAILED with:
> TypeError: A value undefined was yielded that could not be treated as a promise
> 
>     See http://goo.gl/MqrFmX
> 
> From coroutine:
>     at Function.Promise.coroutine (/Users/xxx/node_modules/bluebird/js/release/generators.js:194:17)
>     at main (/Users/xxx/t.js:5:17)
>     at Object.<anonymous> (/Users/xxx/t.js:12:3)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)

With this script:

```
var bluebird = require('bluebird');
var fs = bluebird.promisifyAll(require('fs-extra'));

(function main() {
return bluebird.coroutine(function* (){
	console.log('copying begun')
	yield fs.copy('skel', 'dummydir');
	console.log('All done');

})();

})()
.then(function() {
	console.log('w00t!');
})
.catch(function(err) {
	console.error("FAILED with:\n" + err.toString());
});
```

I am using the npm version (v1.0.0)

**Comment by cmroanirgo** [comment]
Actually, with a bit more research, this begins to make a bit more sense. `bluebird.promisifyAll()` modifies all the async callbacks... But your code expects the original versions, untouched.

Using  this method, copy works as expected. 

```
var fs = require('fs-extra');
fs.copy = bluebird.promisify(fs.copy);
```
