### ISSUE TITLE
v2.1.0 fails on Node.js v4.0.0-v4.5.0

### ISSUE THREAD

**Issue by yourapiexpert** [jprichardson/node-fs-extra#390]
module initialization error: TypeError
at Object.<anonymous> (/var/task/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:6:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/fs-extra/lib/copy-sync/copy-sync.js:5:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/fs-extra/lib/copy-sync/index.js:2:13)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/fs-extra/lib/index.js:16:12)

**Comment by yourapiexpert** [comment]
Hi,

The standard 4.3.  Please do let me know if there's anything I can do to help or more information I can supply.

**Comment by RyanZim** [comment]
The problem commit is 9bef553728ec2a44f0c02d3a42bc118e5d72b4eb. This change requires Node.js v4.5.0+

We wrongly assumed most v4 users were using the latest v4.x.

@jprichardson Advice wanted on how to proceed. Revert and publish a patch version?

**Comment by shumailarshad** [comment]
version 2.1.0 throwing following error on node v4.2.6
"TypeError: Buffer.alloc is not a function"

**Comment by RyanZim** [comment]
fs-extra v2.1.1 published: cfcf3138c3c083eab1b762fc6bbfb3fbd2569e5c. Please upgrade to this new version. This issue should be fixed. Sorry about this.
