### ISSUE TITLE
Missing promise return for 'unlink'

### ISSUE THREAD

**Issue by dionjwa** [jprichardson/node-fs-extra#455]
```
require('fs-extra').unlink('test').catch((err) => {console.log('Got error in promise', err);});
```
It doesn't seem to be returning a promise:

```
TypeError: Cannot read property 'catch' of undefined
    at repl:1:35
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:219:10)
    at REPLServer.Interface._line (readline.js:561:8)
    at REPLServer.Interface._ttyWrite (readline.js:838:14)
> Error: ENOENT: no such file or directory, unlink 'test'
    at Error (native)

```

**Comment by dionjwa** [comment]
My bad, this was due to some kind of npm import error.
