### ISSUE TITLE
Failures to build under iojs and older versions of node

### ISSUE THREAD

**Issue by donkeybonks** [jprichardson/node-fs-extra#494]
Because of ES5

i.e.
```
/home/travis/build/zettaforge/unity-module-scripts/node_modules/fs-extra/lib/util/assign.js:5

  const args = [].slice.call(arguments).filter(i => i)

                                               ^

SyntaxError: missing ) after argument list

    at exports.runInThisContext (vm.js:53:16)

    at Module._compile (module.js:413:25)

    at Object.Module._extensions..js (module.js:448:10)

    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/zettaforge/unity-module-scripts/node_modules/istanbul/lib/hook.js:109:37)

    at Module.load (module.js:355:32)

    at Function.Module._load (module.js:310:12)

    at Module.require (module.js:365:17)

    at require (module.js:384:17)

    at Object.<anonymous> (/home/travis/build/zettaforge/unity-module-scripts/node_modules/fs-extra/lib/index.js:3:16)

    at Module._compile (module.js:430:26)

    at Object.Module._extensions..js (module.js:448:10)
```

Not really sure where to go with this. If I pin to an old dep, then I risk dependency hell. But the only other option is to drop support for old nodes (heaps of people still run old nodes) and iojs.

**Comment by donkeybonks** [comment]
Ah, you need to use ~`2.0.0` for really old nodes.

**Comment by jprichardson** [comment]
> Ah, you need to use ~2.0.0 for really old nodes.

Correct.
