### ISSUE TITLE
RemoveSync doesnt  delete files on windows?

### ISSUE THREAD

**Issue by Jakovb** [jprichardson/node-fs-extra#590]
Tested on Windows 10/8/7

So, deal is i have an desktop version of an app.
Once i run  fs.removeSync(root_dir) It only deletes files that are not being used at the moment. 
Example. My library of images gets deleted, but my db files and others dont. This is not desired outcome so I am wondering if this is related to Account permission stuff or whatnot on windows (files being used since app is still running when removeSync is being called). Any way I could flag the for delete instead of deleting them right away, like unlink does? Any other func that i could use ?

Let me know if you know anything about it. Thanks!

**Comment by pyxis828** [comment]
I am having the same issue -- I get: "ENOTEMPTY: directory not empty, rmdir 'C:\MyFilePathHere\'  when trying removeSync on a non-empty file path.  I am running on Windows 10.

**Comment by JakovBradvica** [comment]
Can you try deleting those files with shift+delete when your app is running. Could be permission issue you are experiencing!

**Comment by pyxis828** [comment]
I was able to manually delete the folder with no problem.

**Comment by RyanZim** [comment]
Deleting files on Windows is an all-around pain. To my knowledge, there's no way to delete them while they're locked.

**Comment by adamskwersky** [comment]
emptyDirSync has the same problem. If you try to use this on a directory that still has files you get the ENOTEMPTY error. But rmdirSync on "C:\myworkspace\git\myproject\test\out\decomposed" works! 

This is the stack trace:

     Error: ENOTEMPTY: directory not empty, rmdir 'C:\myworkspace\git\myproject\test\out\decomposed\some\subdirectory'
      at Object.fs.rmdirSync (fs.js:846:18)
      at rmkidsSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:304:27)
      at rmdirSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
      at rimrafSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
      at options.readdirSync.forEach.f (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
      at rmdirSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:281:7)a
      at rimrafSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
      at options.readdirSync.forEach.f (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
      at Array.forEach (<anonymous>)
      at rmkidsSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
      at rmdirSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
      at Object.rimrafSync [as removeSync] (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
      at items.forEach.item (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\empty\index.js:39:12)
      at Array.forEach (<anonymous>)
      at Object.emptyDirSync (C:\myworkspace\git\myproject\node_modules\fs-extra\lib\empty\index.js:37:9)
      at Context.<anonymous> (C:\myworkspace\git\myproject\test\mytests.js:84:16)

**Comment by RyanZim** [comment]
As far as I know, there's no way to fix this, so closing out.
