### ISSUE TITLE
copySync sometime call unlinkSync

### ISSUE THREAD

**Issue by hong-duc** [jprichardson/node-fs-extra#601]
- **Operating System:**
Manjaro Linux
- **Node.js version:**
8.11.1
- **`fs-extra` version:**
^6.0.1

Sometime when I call copySync it fail beacause it call unlinkSync to try to delete the dest dir

```
Error: EISDIR: illegal operation on a directory, unlink '/home/hongduc/UploadServer/release/hutech-qhdn/web-client/dist'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at mayCopyFile (/home/hongduc/Project/javascript/hutech-qhdn/web-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
    at onFile (/home/hongduc/Project/javascript/hutech-qhdn/web-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:47)
    at getStats (/home/hongduc/Project/javascript/hutech-qhdn/web-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:47:39)
    at startCopy (/home/hongduc/Project/javascript/hutech-qhdn/web-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:10)
    at Object.copySync (/home/hongduc/Project/javascript/hutech-qhdn/web-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:10)
    at Object.<anonymous> (/home/hongduc/Project/javascript/hutech-qhdn/web-client/tool/deploy.js:25:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32
```

And this is the code I use
```
fse.copySync('./dist', deployPath + '/dist')
```

**Comment by manidlou** [comment]
@hong-duc seems like you are copying a src `file` to a dest `directory`. With `fs-extra` you cannot copy a file to a directory. For instance, you cannot do `fse.copy('srcfile.js', 'destDir')`. You have to explicitly specify your dest file name.

So my suggestion is we change the code to check the dest type when src is a file. We do this when src is a directory, surprisingly we didn't think about the reverse case! :grin:

**Comment by hong-duc** [comment]
@manidlou sorry I should have include the code I use
```
fse.copySync('./dist', deployPath + '/dist')
```
I am copy directory to directory, but sometime `fs-extra` try to delete the dest directory, sometime not :smiley:

**Comment by RyanZim** [comment]
@manidlou Any ideas here?

**Comment by manidlou** [comment]
@hong-duc will you please use the latest version `7.0.0` of `fs-extra` and see if you still experience the issue?

**Comment by hong-duc** [comment]
No error in version `7.0.0` thanks
