### ISSUE TITLE
TypeError: called Async suffix on non-function getter

### ISSUE THREAD

**Issue by LoganDark** [jprichardson/node-fs-extra#604]
- **Operating System:** macOS 10.14 Mojave 18A326g
- **Node.js version:** v10.1.0
- **`fs-extra` version:** 6.0.1

```
LoganDark@base ~/n/backend> ./node_modules/.bin/ts-node index.ts 

/Users/LoganDark/nitrogen/backend/node_modules/pifall/index.js:84
              throw new TypeError('called Async suffix on non-function getter');
                    ^
TypeError: called Async suffix on non-function getter
    at Object.get [as promisesAsync] (/Users/LoganDark/nitrogen/backend/node_modules/pifall/index.js:84:21)
    at Object.keys.forEach.key (/Users/LoganDark/nitrogen/backend/node_modules/fs-extra/lib/fs/index.js:54:20)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/LoganDark/nitrogen/backend/node_modules/fs-extra/lib/fs/index.js:48:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
```

~~May be related to #578.~~

NODE V8.11.3 WORKS

**Comment by RyanZim** [comment]
Not sure how this relates to `fs-extra`; looks to be an error in `pifall`.

**Comment by LoganDark** [comment]
I'm not sure either, but this ruins `fs-extra` on node versions > 8

**Comment by RyanZim** [comment]
`fs-extra` runs just fine on Node 10; the issue seems to be with `pifall`

**Comment by LoganDark** [comment]
Well, I don't use `pifall`, and the traceback is complaining about `fs-extra`

**Comment by JPeer264** [comment]
It seems no dependency of `fs-extra` is using `pifall`:

```sh
$ npm ls | grep pifall
```

The problem should be somewhere else.

**Comment by LoganDark** [comment]
It seemed like another dependency was modifying the cached `fs` with `pifall` and fs-extra's 'export all keys' was trying to export that too. I updated it and everything works fine (in fact that particular dependency switched straight from modifying `fs` to `fs-extra`! :P).
