### ISSUE TITLE
npm run lint fails with standard-markdown@4.0.2

### ISSUE THREAD

**Issue by mbargiel** [jprichardson/node-fs-extra#631]
**Problem:**
After cloning this repo in order to investigate an Issue and submit a PR (current master head: 287f234817871976f80e28ab50b339471e4c4223) and running `npm install`, I ran into the following problem when I ran `npm run lint`:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at Command.<anonymous> (/Users/maximeb/code/playground/node-fs-extra/node_modules/standard-markdown/cli.js:32:28)
    at Command.listener (/Users/maximeb/code/playground/node-fs-extra/node_modules/commander/index.js:315:8)
    at emitNone (events.js:106:13)
    at Command.emit (events.js:208:7)
    at Command.parseArgs (/Users/maximeb/code/playground/node-fs-extra/node_modules/commander/index.js:665:12)
    at Command.parse (/Users/maximeb/code/playground/node-fs-extra/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/maximeb/code/playground/node-fs-extra/node_modules/standard-markdown/cli.js:40:4)
    at Module._compile (module.js:652:30)
```

**Root cause:**
I tracked this down to a problem in `standard-markdown@4.0.2` which has been fixed in `5.*`. EDIT: I thought `standard-markdown@4.0.1` did not have this issue, but apparently I'm getting the same behavior.

`standard-markdown` issue: https://github.com/zeke/standard-markdown/issues/24
`standard-markdown` fix commit: https://github.com/zeke/standard-markdown/commit/7b83a0e0a93be3a4a9dac3a94521f98bc43f8afb

**Suggested fixes:**
- Implement a workaround in `package.json` as per https://github.com/octokit/rest.js/pull/974/commits/47e23ff03ab68cb016b9d45e1d1674dde4e02227 (*EDIT: This seems to work with 4.0.1 and 4.0.2, potentially an easy fix*)
- Create a `package-lock.json` so that contributors can reproduce your own setup
- Force 4.0.1 as the version for `standard-markdown` (*EDIT: This does not seem to actually fix the issue!*)
- Upgrade it to a version at least `5.0.0` (possibly not desirable: https://github.com/zeke/standard-markdown/commit/83a6fd39f92ef7d19183ffd71b359b6500ae5623)

**Comment by RyanZim** [comment]
Yes, I know about this; it's broken for me as well, and is on my list to fix (we need to upgrade `standard` & `standard-markdown` to the latest versions). Of course, if you'd like to do a PR, that'd be just fine too!

BTW, thanks for the detailed and clearly worded issue; it's a breath of fresh air.

**Comment by RyanZim** [comment]
Closing in favor of https://github.com/jprichardson/node-fs-extra/issues/648.
