### ISSUE TITLE
Failing 'copy() preserve timestamp' tests on MacOS

### ISSUE THREAD

**Issue by mbargiel** [jprichardson/node-fs-extra#632]
- **Operating System:**
MacOS High Sierra 10.13.6

- **Node.js version:**
8.11.3

- **`fs-extra` version:**
`master` branch (commit 287f234)

After cloning the `node-fs-extra` repo, running `npm test` causes the following failures in two tests:

```
1) copy() - preserve timestamp
       > when timestamp option is true
         should have the same timestamps on copy:

      Uncaught AssertionError [ERR_ASSERTION]: 1539276917881 === 1539276917885
      + expected - actual

      -1539276917881
      +1539276917885
      
      at /Users/mbargiel/code/node-fs-extra/lib/copy/__tests__/copy-preserve-time.test.js:52:18
      at Array.forEach (<anonymous>)
      at copy (lib/copy/__tests__/copy-preserve-time.test.js:36:15)
      at /Users/mbargiel/code/node-fs-extra/node_modules/graceful-fs/polyfills.js:239:18
      at FSReqWrap.oncomplete (fs.js:135:15)

  2) copySync() - preserveTimestamps option
       > when preserveTimestamps option is true
         should have the same timestamps on copy:

      AssertionError [ERR_ASSERTION]: 1539276922782 === 1539276922784
      + expected - actual

      -1539276922782
      +1539276922784
      
      at /Users/mbargiel/code/node-fs-extra/lib/copy-sync/__tests__/copy-sync-preserve-time.test.js:49:18
      at Array.forEach (<anonymous>)
      at Context.it (lib/copy-sync/__tests__/copy-sync-preserve-time.test.js:35:13)

  3) utimes
       hasMillisResSync()
         should return a boolean indicating whether it has support:

      AssertionError [ERR_ASSERTION]: true === false
      + expected - actual

      -true
      +false
      
      at Context.it (lib/util/__tests__/utimes.test.js:31:49)
```

**Comment by mbargiel** [comment]
I believe this is why: https://en.wikipedia.org/wiki/MacOS_High_Sierra#Apple_File_System

**Comment by RyanZim** [comment]
Isn't this a dupe of https://github.com/jprichardson/node-fs-extra/issues/571?

**Comment by mbargiel** [comment]
Oh, yeah, it seems so. My bad, I didn't properly before opening it. Closing this one.
