### ISSUE TITLE
fs.CopySync ENONET Error

### ISSUE THREAD

**Issue by SteinNs** [jprichardson/node-fs-extra#635]
- Operating System:linux
- Node.js version:8.11.0
- `fs-extra` version: 7.0.0
Hello，I got an error when using fse.copySync as follow.
```
Error: ENOENT: no such file or directory, unlink '/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/ssrfile/ae-pc-pcShopHead/index.node.js'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at mayCopyFile (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_fs-extra@7.0.0@fs-extra/lib/copy-sync/copy-sync.js:57:8)
    at onFile (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_fs-extra@7.0.0@fs-extra/lib/copy-sync/copy-sync.js:52:10)
    at getStats (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_fs-extra@7.0.0@fs-extra/lib/copy-sync/copy-sync.js:46:44)
    at startCopy (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_fs-extra@7.0.0@fs-extra/lib/copy-sync/copy-sync.js:36:10)
    at Object.copySync (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_fs-extra@7.0.0@fs-extra/lib/copy-sync/copy-sync.js:31:10)
    at FSWatcher.watcher.on.on.path (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/app/service/module.js:83:8)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (/home/admin/ae-merchant-nodeservices-s/target/ae-merchant-nodeservices-s/node_modules/_chokidar@2.0.4@chokidar/index.js:199:15)

```
I don't know why when destPath wasn't exist, fse still called mayCopyFile function and  fs.unlinkSync which led to the error. In fact,when destPath wasn't exist, it  should called copyFile instead.
```
function onFile (srcStat, destStat, src, dest, opts) {
  if (destStat === notExist) return copyFile(srcStat, src, dest, opts)
  return mayCopyFile(srcStat, src, dest, opts)
}
```

**Comment by RyanZim** [comment]
Please post a reduced test case repo

**Comment by RyanZim** [comment]
Closing for lack of reply.
