### ISSUE TITLE
pin version of graceful-fs to v4.1.11

### ISSUE THREAD

**Issue by sw-yx** [jprichardson/node-fs-extra#645]
graceful-fs seems to have published a buggy release with v4.1.12

https://github.com/isaacs/node-graceful-fs/issues/139

https://github.com/isaacs/node-graceful-fs/issues/138

causing errors like this:

```bash

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/swyx/Netlify/netlify-react-ui/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/swyx/Netlify/netlify-react-ui/node_modules/fs-extra/lib/fs/index.js:4:12)

```

suggest temporarily pinning the version to v4.1.11 since this is causing a lot of downstream errors everywhere in node ecosystem

**Comment by sw-yx** [comment]
resolved downstream
