### ISSUE TITLE
Error: Cannot find module './fs.js'

### ISSUE THREAD

**Issue by zjh12580** [jprichardson/node-fs-extra#671]
"fs-extra": "^5.0.0",
node  v11.3.0
webpack v4.30.0
npm v6.4.1

npm install 

Error: Cannot find module './fs.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/godofdeath/work/weex/logweexmodule/node_modules/graceful-fs/polyfills.js:1:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed.You must install peer dependencies yourself.

**Comment by manidlou** [comment]
Seems like your environment is browser. `fs-extra` doesn't work on browsers.
