### ISSUE TITLE
[8.0.0] RangeError: Maximum call stack size exceeded at moveSync

### ISSUE THREAD

**Issue by williamcruzme** [jprichardson/node-fs-extra#678]
- **Operating System:**
Windows [Version 10.0.17763.475]
- **Node.js version:**
v11.14.0
- **`fs-extra` version:**
v8.0.0

In the v7.0.1 is working fine!

```js
// Move
paths.forEach(path => (
  fs.moveSync(`${src}/${path}`, `${dest}${applyConfig(path, config)}`, { overwrite: true })
));
```

`(node:5924) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at isPathSeparator (path.js:38:25)
    at Object.resolve (path.js:169:13)
    at Object.toNamespacedPath (path.js:555:32)
    at Object.statSync (fs.js:869:41)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:143:21)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)
    at checkParentPathsSync (C:\Users\johne\Documents\Elaniin Tech Company\elaniin-cli\node_modules\fs-extra\lib\util\stat.js:154:10)`

**Comment by RyanZim** [comment]
@manidlou any ideas?

**Comment by manidlou** [comment]
I think one way to fix this is wrapping `checkParentPathsSync()` recursive call in `setTimeout()`. Or maybe we could remove checking parent paths from move since i primarily used that to fix copying bind-mounted dirs and move uses copy for cross device operation anyway.

**Comment by efstathiosntonas** [comment]
Same here with `copySync`, v8.0.0

**Comment by manidlou** [comment]
@williamcruzme @efstathiosntonas can you please provide us a repo test case?

**Comment by williamcruzme** [comment]
@manidlou Yes, I've made you a collaborator in a repository where it contains a simple moveSync.

**Comment by manidlou** [comment]
Thanks @williamcruzme! I'll take a look.

**Comment by manidlou** [comment]
@williamcruzme I cannot reproduce the issue by running your example!

**Comment by williamcruzme** [comment]
@manidlou Maybe it has to do with the operating system and the version of Node.js

**Comment by manidlou** [comment]
Possibly! I am running it on Ubuntu 18.04 and node 10.9.0

**Comment by dumbmatter** [comment]
I made a very small test case that produces an error message like this: https://github.com/dumbmatter/node-fs-extra-issue-678

The code is just:

    const fse = require("fs-extra");

    fse.removeSync("build");
    fse.mkdirSync("build");
    fse.copySync("a/b", "build");

Seems that it doesn't like the first argument to copySync containing a slash. But it works fine with fs-extra 7.0.1.

I'm not totally sure if this is the same issue noticed by others, but the error message is the same: "Maximum call stack size exceeded". Let me know if you want me to create a separate issue. And thanks for all your work on fs-extra, it is much appreciated :)

**Comment by manidlou** [comment]
@dumbmatter thanks for your comment. I was able to recreate the issue using your example.

**Comment by efstathiosntonas** [comment]
My case is different, I’ll post an example later today
-- 
Sent from my phone

**Comment by manidlou** [comment]
thanks @efstathiosntonas! I am sure that will help too.

In the meantime, I think I found the bug! I will make PR shortly with a possible fix.
