### ISSUE TITLE
fs.pathExists not found

### ISSUE THREAD

**Issue by lynxionxs** [jprichardson/node-fs-extra#714]
- **Operating System: Ubuntu 18.04**
- **Node.js version: v8.10.0**
- **`fs-extra` version: v8.1.0**

When i import fs.pathExists function it shows the method doesnt exist. "pathExists" is not in the fs object with the other methods.

```javascript
const fs = require('fs-extra');

console.log(fs.hasOwnProperty('pathExists')); // false

(async () => {
    let exists = await fs.pathExists('./path/file.txt');
    console.log(exists);
    /*
    RESULT:
    TypeError: fs.pathExists is not a function
        at Object.<anonymous> (/home/user/nodejs/test.js:4:4)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Function.Module.runMain (module.js:693:10)
        at startup (bootstrap_node.js:188:16)
        at bootstrap_node.js:609:3
    */
})();
```

**Comment by RyanZim** [comment]
Try reinstalling `fs-extra`?

**Comment by lynxionxs** [comment]
@RyanZim i tried reinstalling but still showing the same error

**Comment by RyanZim** [comment]
Can you make a reduced test case repo?

**Comment by lynxionxs** [comment]
I dont know how to do that. It's ok i just made a custom function using native ```fs.access()``` to fix it. I dont wana stress about this
