### ISSUE TITLE
Crash on copySync in 9.0.0

### ISSUE THREAD

**Issue by jlippold** [jprichardson/node-fs-extra#776]
- **Operating System:**
mac

- **Node.js version:**
8.94

- **`fs-extra` version:**
9.0.0

I'm doing a super simple copy operation

```
fs.copySync('./src/inject', './public/inject'); 
```

and I'm getting a crash

```

XXX/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (XXX/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Comment by jlippold** [comment]
rolled back to 8.0.0 and it works

**Comment by manidlou** [comment]
@jlippold `fs-extra` v9 requires node v10+. That's stated in the changelog. That's `optional catch binding` that requires node v10+ to work.

**Comment by jlippold** [comment]
Ok, that wasn't super obvious to me. Too bad there's not better error handling, or some kind of warning when using < 10
