### ISSUE TITLE
"try {...} catch {...}" gives unexpected token error on the '{' after catch.  'catch (error) {...}" fixes it.

### ISSUE THREAD

**Issue by Detnator-Neo** [jprichardson/node-fs-extra#832]
- **Operating System:**
macOS 10.15.6 Catalina (latest)
- **Node.js version:**
$ node -v -> v8.11.2
- **`fs-extra` version:**
9.0.1 -- npm'd an hour ago.  

First, disclaimers: 
1. Relative newbie to JS and node.  I've learned a lot, but still a lot more to learn.  I haven't used `try...catch` myself yet, though I'm familiar with the principles of it from other languages, and reading at least this documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#try...catch_statement shows it seems to be pretty straight forward and more or less the same as other languages I'm familiar with.
2. My node is v8 -  the one included with this version of macOS (it seems odd that macOS is so far behind in node versions but ok...).  The "engines" element in the package.json says node 10+ is required.  So there's something new in node 9 or 10 that removes the need for the `(error)` part?  At least the javascript documentation linked above seems to say it's still needed (called `catchID` there).
3. So it seems very strange to me that this particular error hasn't been reported by anyone else yet, or even found originally by the dev, as it seems like a basic syntax error?  How has this code worked for anyone else to date?  There's something I'm missing?  Love to know what that is.

All that said, here's the issue in what's probably more detail than necessary, but just in case it helps...

**Here's what I did:**
1. in terminal: 
`npm install fs-extra`
2. in myjsfile.js:
```
const fs = require('fs-extra');
<a bunch of other code>
```
3. terminal: 
`node myjsfile.js`

**Result:** 
```
</path/to/my/node/directory>/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/10 DT/10 Home/davidthorp/Library/Script Libraries/JS/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

```

Ok... that's odd. As far as I can tell it doesn't even make it to my code. This is still within the initial `require`.

I look inside that file.  Change `} catch {` to `} catch (error) {` and try `node myjsfile.js` again.

Result: the same `SyntaxError` but in a different fs-extra file.

Ok, new strategy.  Open all the js files in fs-extra in BBEdit, do a find all for `} catch {`. Replace all with `} catch (error) {` and try `node myjsfile.js` again.

Result: Everything works great.

Am I missing something, or is this a genuine bug/issue in fs-extra?

**Comment by Detnator-Neo** [comment]
Update:  I'm new to git as well, so didn't figure this out till just now.  I see that this issue **has** been reported a number of times before and the answer seems to be that a node 9 or 10 supports ES2019 which supports `catch` without the `catchID`.

Seems to be a common issue on Mac because macOS comes with node, but its node is old.  Why Apple doesn't include a much newer version seems odd, but I guess that is what it is.

I'll close this now.  I guess I, and all us other Mac users, need to manually download a newer node and work with that instead of the default one.  I guess it's reasonable that that not be `fs-extra`'s problem.

Sorry for the noise, though maybe all this will help someone else in the future.
