### ISSUE TITLE
jest: graceful-fs - TypeError: Object prototype may only be an Object or null: undefined at Function.setPrototypeOf (<anonymous>)

### ISSUE THREAD

**Issue by hoigo** [jprichardson/node-fs-extra#868]
I currently get the following error executing my unit tests with Jest:

 ● Test suite failed to run

    TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

    > 4 | var fsExtra = require('fs-extra');
        |               ^
      at ../dist/server/node_modules/graceful-fs/polyfills.js:139:39
      at patch (../dist/server/node_modules/graceful-fs/polyfills.js:141:5)
      at patch (../dist/server/node_modules/graceful-fs/graceful-fs.js:104:3)
      at Object.<anonymous> (../dist/server/node_modules/graceful-fs/graceful-fs.js:96:18)
      at Object.<anonymous> (../dist/server/node_modules/fs-extra/lib/fs/index.js:5:12)
      at Object.<anonymous> (../dist/server/node_modules/fs-extra/lib/index.js:5:6)

I'm using Node.js 14.15.0, fs-extra 9.1.0 and graceful-fs 4.2.3

Do you have any hints?

**Comment by RyanZim** [comment]
No ideas; can you try to make a reduced test case?

**Comment by hoigo** [comment]
There were problems with the environment.

**Comment by shivam-2202** [comment]
Hey, I am also facing same problem. Can you please help on how to resolve.

**Comment by cnpatric** [comment]
gotta love answers like those. @hoigo please use "fixed it" next time so people that stumble over this have even less information about how to solve this.

**Comment by hoigo** [comment]
@cnpatric ok, I forgot to mention that I fixed it.

**Comment by hoigo** [comment]
> Hey, I am also facing same problem. Can you please help on how to resolve.

@shivam-2202 it's been a while since I fixed it. well, I don't remember what I've done.
