### ISSUE TITLE
Incompatible with Nexe packaging  tool while using fs-extra 10.0.0

### ISSUE THREAD

**Issue by donthijackthegit** [jprichardson/node-fs-extra#909]
- **Operating System:**Ubuntn 20.04.1
- **Node.js version:** v12.20.2/v14.17.1

- **`fs-extra` version:** 10.0.0

I am using Nexe to package my service into an executable file. Compilation was success, but when I run the app, I got below error message:
```
 }, 'name', { value: fn.name })
                         ^

TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/***/dist/nexe/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/***/dist/nexe/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/***/dist/nexe/node_modules/fs-extra/lib/index.js:5:6)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

```
I switch back to fs-extra 9.1.0 everything works fine.

Cannot reproduce if run directly via node.

**Comment by RyanZim** [comment]
This is a bug with Nexe, it looks like they don't support [`fs.realpath.native`](https://nodejs.org/api/fs.html#fs_fs_realpath_native_path_options_callback).
