### ISSUE TITLE
copySync error when a subdirectory is a symbol link

### ISSUE THREAD

**Issue by elgs** [jprichardson/node-fs-extra#937]
- **Operating System:** macOS Monterey 12.1
- **Node.js version:** v17.3.0
- **`fs-extra` version:** 10.0.0

I have the following directory structure (src/lib is a symbol link):
```
├── build
│   └── lib -> ../lib
├── build.js
├── lib
└── src
    └── lib -> ../lib
```

And build.js:
```js
const fse = require('fs-extra');
fse.copySync('src/', 'build/');
```

Basically I want to copy everything inside src to build, and I only want to copy the src/lib as a symbol link to build, not the content. When I ran build.js, I got the following error:
```
/private/tmp/e$ node build.js
/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:148
      throw new Error(`Cannot copy '${resolvedSrc}' to a subdirectory of itself, '${resolvedDest}'.`)
      ^

Error: Cannot copy '../lib' to a subdirectory of itself, '../lib'.
    at onLink (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:148:13)
    at getStats (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:45)
    at startCopy (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:122:10)
    at /private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:39
    at Array.forEach (<anonymous>)
    at copyDir (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:23)
    at onDir (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:105:10)
    at getStats (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at handleFilterAndCopy (/private/tmp/e/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
```

I am aware of the `dereference: true` option, but that would copy everything from the lib to the build directory, which is not what I wanted.

**Comment by elgs** [comment]
Now I am doing a workaround like this, and it seems to work, but ideally the library could handle this situation:

```js
const fse = require('fs-extra');

const filter = (src, dest) => {
   const destStats = fse.existsSync(dest) && fse.lstatSync(dest);
   return !destStats?.isSymbolicLink?.();
};

fse.copySync('src/', 'build/', { filter });
```

**Comment by RyanZim** [comment]
The error message isn't terribly clear here, but basically `build/lib` already exists as a symlink, so when you try to copy to it, you're effectively copying to `lib`. Of course, you can't make `lib` itself a symlink to itself, so it errors out. This would work fine if `build/lib` didn't already exist.

**Comment by elgs** [comment]
@RyanZim yeah it works exactly as what you said. So is there a way to overwrite a symbol link in this case?

**Comment by RyanZim** [comment]
Not directly; your best bet would be to `remove` it first.
