### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by paddotk** [jprichardson/node-fs-extra#958]
- **Operating System:** Windows 11
- **Node.js version:** 16.14.2
- **`fs-extra` version:** 10.1.0

I get an error 'process is not defined' when I try to import this lib. I'm using this in NodeJS.

Full error stack:
```
Uncaught ReferenceError: process is not defined
    at node_modules/graceful-fs/polyfills.js (polyfills.js:3:15)
    at __require (chunk-IGMYUX52.js?v=f6b96a9a:40:50)
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:2:17)
    at __require (chunk-IGMYUX52.js?v=f6b96a9a:40:50)
    at node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require (chunk-IGMYUX52.js?v=f6b96a9a:40:50)
    at node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require (chunk-IGMYUX52.js?v=f6b96a9a:40:50)
    at dep:fs-extra:1:16
```

**Comment by RyanZim** [comment]
Looks like you're using some kind of code bundling?

**Comment by paddotk** [comment]
@RyanZim Yes, I'm using Webpack in my project.

**Comment by RyanZim** [comment]
Webpack is probably bundling your code for browser, and not allowing process to be defined. Webpack is primarily intended for browser code; Node.js code isn't generally bundled.
