### ISSUE TITLE
Fireworm reporting "File should always be initialied with stat"

### ISSUE THREAD

**Issue by Anaerin** [jprichardson/node-fs-extra#961]
- **Operating System:** FreeBSD
- **Node.js version:** v14.18.1
- **`fs-extra` version:** 5.0.0

Seem to be getting this odd error - Is this something to do with you?
```
Uncaught Exception: AssertionError [ERR_ASSERTION]: File should always be initialied with stat
AssertionError [ERR_ASSERTION]: File should always be initialied with stat
    at /usr/local/games/minecraft/node_modules/fireworm/lib/file.js:45:7
    at FSReqCallback.oncomplete (fs.js:192:5)
About to exit with code 1
```

**Comment by RyanZim** [comment]
Not seeing fs-extra anywhere in that stack trace; unrelated to this library.
